version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - auth
      - front
    ports:
      - 3000:3000
      - 3443:3443
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx

  front:
    build: ./front/make.todo
    container_name: front
    volumes:
      - './front/make.todo/:/app'
    depends_on:
      - auth

  auth:
    container_name: auth
    build: ./back/services/auth
    environment:
      DATABASE_URL: "postgres://admin:admin@db:5432/todo"
      COOKIE_SALT: "SUPER_SALTY"
    volumes:
      - ./back/services/auth/:/app
    depends_on:
      - db

  todos:
    build: ./back/services/todos
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back/services/todos:/app
    depends_on:
      - db
      - auth

  db:
    container_name: db
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./deploy/psql/:/docker-entrypoint-initdb.d
      - ./tmp/pgdata/:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
