version: "3.8"
services:
  web:
    build: ./front/make.todo
    volumes:
      - './front/make.todo/:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true    
    depends_on:
      - auth

  auth:
    build: ./back/cmd/auth
    ports:
      - '8000:8000'
    volumes:
      - ./back/cmd/auth/:/app
 