version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - auth
      - front
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx

  front:
    build: ./front/make.todo
    container_name: front
    volumes:
      - './front/make.todo/:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true    
    depends_on:
      - auth

  auth:
    container_name: auth
    build: ./back/cmd/auth
    volumes:
      - ./back/cmd/auth/:/app
 