version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - auth
      - front
    ports:
      - 3000:3000
      - 3443:3443
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx

  front:
    build: ./front/make.todo
    container_name: front
    volumes:
      - './front/make.todo/:/app'
    depends_on:
      - auth

  auth:
    container_name: auth
    build: ./back/cmd/auth
    environment:
      DATABASE_URL: "postgres://admin:admin@db:5432/todo"
    volumes:
      - ./back/cmd/auth/:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./deploy/psql/:/docker-entrypoint-initdb.d
      - ./tmp/pgdata/:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
 