name: Auth Service Image CI

env:
  SERVICE_PATH: back/services/auth

on:
  pull_request:
    branches: [main]
    paths:
      - ${{ env.SERVICE_PATH }}/**
      - .github/workflows/auth.yml

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v3

      - name: Tests
        working-directory: ${{ env.SERVICE_PATH }}
        run: go test ./...

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build auth service image
        run: docker build ${{ env.SERVICE_PATH }} --file ${{ env.SERVICE_PATH }}/Dockerfile --tag auth:$(date +%s)
