name: Repo format

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: github-action-auto-format
        uses: cloudposse/github-action-auto-format@v0.12.0
