name: Frontend Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - front/make.todo/**
      - .github/workflows/frontend.yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Build frontend image
        run: docker build . --file ./front/make.todo/Dockerfile --tag front:$(date +%s)
