name: Todos Service Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - back/services/todos/**
      - .github/workflows/todos.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build todos service image
        run: docker build ./back/services/todos --file ./back/services/todos/Dockerfile --tag todos:$(date +%s)
