name: Todo Service Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - back/services/todo/**
      - .github/workflows/todo.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build todo service image
        run: docker build . --file ./back/services/todo/Dockerfile --tag todo:$(date +%s)
